project:
  type: website
  output-dir: docs

#language: _language.yml
lang: ja

website:
  site-url: "https://www.kazuhiroterashita.com/"
  title: "Kazuhiro Terashita"
  page-footer: "Copyright 2024, Kazuhiro Terashita. Powered by [Quarto](https://quarto.org/)"
  google-analytics: "G-9CQKQ3Z1YQ"
  favicon: "pic/favicon2.png"
  navbar:
    search: true
    left:
      - text: "CV"
        href: cv/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
    right: 
      - icon: twitter
        href: https://twitter.com/namiterashita
      - icon: instagram
        href: https://www.instagram.com/namiterashita/
      - text: "{{< iconify bi threads size=20px >}}" #quarto add mcanouil/quarto-iconify の実行が必要
        href: https://www.threads.net/@namiterashita
      - text: "{{< iconify material-symbols edit-note size=23px >}}"
        href: https://note.com/namiterashita
      - icon: github
        href: https://github.com/namiterashita
      - icon: caret-right
        href: https://researchmap.jp/kazuhiroterashita

format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: source

