project:
  type: website
  output-dir: docs

#language: _language.yml
lang: ja

website:
  site-url: "https://www.kazuhiroterashita.com/"
  title: "Kazuhiro Terashita"
  page-footer: "Copyright 2023, Kazuhiro Terashita. Powered by [Quarto](https://quarto.org/)"
  favicon: "pic/favicon.png"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "CV"
        href: CV/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
    right: 
      - icon: twitter
        href: https://twitter.com/namiterashita
      - icon: instagram
        href: https://www.instagram.com/namiterashita/
      - icon: github
        href: https://github.com/namiterashita
      - icon: map
        href: https://researchmap.jp/kazuhiroterashita

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

