---
title: "Research"
date-modified: today
link-external-newwindow: true
#link-external-icon: true
toc: true
toc-depth: 5
---

### Thesis & Dissertation

1.  **寺下和宏**（2023）「韓国における女性団体とジェンダー政策――市民社会の政治的帰結に関する実証研究」神戸大学法学研究科博士学位論文.

2.  **寺下和宏**（2019）「韓国における『慰安婦』運動の政治分析 ：『記憶する』アドボカシーと対立構造」, 立命館大学国際関係研究科修士学位論文.

3.  **寺下和宏**（2017）「ヘイトスピーチと対抗する市民構造：差別問題に関するアドボカシーの検証」, 『在素知贅　-2017年坂本治也ゼミ研究論文集-』（2016年度関西大学坂本治也ゼミ提出論文）. [[Reference](http://www2.itc.kansai-u.ac.jp/~haruya/zemipage.html)]{.btn}

### Journal Articles

1.  **寺下和宏**（2023）「ジェンダー予算とは何か：文献レビューと韓国の事例から」, 『六甲台論集. 法学政治学編』69(2): 99-123. [[DOI](https://doi.org/10.24546/0100481136) [CiNii](https://cir.nii.ac.jp/crid/1390577133290861824)]{.btn}

2.  **寺下和宏**（2022）「市民社会組織のブーメラン戦略はいかなる政治的帰結をもたらすのか：日本におけるヘイトスピーチ解消法の事例分析」『ノンプロフィット・レビュー』21（12）: 81-93, **査読あり**.\
    [[DOI](https://doi.org/10.11433/janpora.NPR-D-21-00004) [CiNii](https://cir.nii.ac.jp/crid/1390010292841684224)]{.btn}

3.  **寺下和宏**（2022）「河川行政における官民協働の質的比較分析（QCA）：行政の実施構造と民間団体の戦略に注目して」, 『季刊行政管理研究』（177）: 46-60, **査読あり**.\
    [[Reference](http://www.iam.or.jp/quarterly/par177.html) [CiNii](https://cir.nii.ac.jp/crid/1522543656137653248)]{.btn}

### Misc.

1.  **寺下和宏**（2022）「書評:Steel, G. (ed.). Beyond the Gender Gap in Japan, University of Michigan Press, 2019」, 『選挙研究』38(1): 126-7.

### Presentation

#### International Conference

1.  **Terashita, Kazuhiro**, "How Do Women's Organizations Influence Welfare Budgets? : Empirical Evidence from Local Governments in South Korea." International Society for Third-Sector Research 15th International Conference, Montreal, Oral presentation, July 2022, **査読あり**. [[Reference](https://tinyurl.com/223gr3pz)]{.btn}

2.  **Terashita, Kazuhiro**. "Strategies and Consequences of Social Movements in Enacting Ordinances: A Qualitative Comparative Analysis of Gender Backlash in Japan." 25th edition of Alternative Futures and Popular Protest, Online, Oral presentation, June 2021. [[Reference](http://www.movements.manchester.ac.uk/afpp/2021-programme/)]{.btn}

#### Domestic Conference

1.  大倉沙江, 三浦まり, 小谷幸, 金美珍, **寺下和宏**, 坂本治也, 菊池遼「パネル：日本の政治・社会におけるジェンダー不平等と女性運動・女性団体：アンケート調査の結果から」,『日本NPO学会第25回年次大会』,京都, 2023年6月. [[資料/ペーパー](https://drive.google.com/drive/folders/1NrWUMTnNxMtU56xFkdjUbeGg3TxQAxMR?usp=sharing)]{.btn}

2.  **寺下和宏**「女性団体・運動は女性の実質的代表に影響を与えるのか：韓国の議会議事録を用いた実証分析」,『日本選挙学会2023年度総会・研究会』,東京, 2023年5月.

3.  **寺下和宏**「自然言語処理（NLP）を用いた抗議イベントデータ作成の半自動化――非英語圏としての韓国を事例に」, 『日本政治学会2022年度研究大会』, 京都, ポスター報告, 2022年10月.

4.  石本めぐみ, 遠藤智子, **寺下和宏**, 大倉沙江「パネル：NPO・市民活動は女性・ジェンダーにどのように向きあうべきか 」, 『日本NPO学会第24回年次大会』, オンライン, 口頭報告（パネリスト/企画者）, 2022年6月.

5.  **寺下和宏**「女性団体は福祉予算にどのような影響を与えるのか：韓国の地方自治体を事例に 」, 『日本公共政策学会2022年度総会・研究大会』, 東京, 口頭報告, 2022年6月.

6.  **寺下和宏**「NPO は女性・ジェンダーにどう向き合ってきたのか：Twitter 投稿のテキストマイニングによる検討」, 『日本 NPO 学会第 23 回年次大会』, オンライン, 口頭報告, 2021 年 6 月.

7.  **寺下和宏**「団体戦略からみるNPO・市民活動参加の規定要因：河川保全運動の質的比較分析を通じて」, 『日本NPO学会第22回年次大会』, オンライン, 口頭報告, 2020年11月.

8.  **寺下和宏**「社会運動の行政施策に対する影響力の分析：河川協力団体制度の事例比較を通じて」, 『日本政治学会2020年度研究大会』, オンライン, 口頭報告, 2020年9月.

9.  **寺下和宏**「ヘイトスピーチに対抗する市民アドボカシーの分析：民団の請願活動と草の根カウンター運動の比較を通じて」, 『日本NPO学会第20回年次大会』, 東京, 口頭報告, 2018年6月.

#### Research Workshop

1.  **寺下和宏**「女性団体はジェンダー政策に影響をもたらすのか：韓国・地方自治体予算の実証分析」, 『ジェンダーと政治研究会』, オンライン, 口頭報告, 2022年3月. [[Reference](https://jpsa-gender.blogspot.com/2022/03/12.html)]{.btn}

2.  **寺下和宏**「女性団体は福祉予算にどのような影響を与えるか：韓国の地方自治体における実証分析」, 『ソーシャルセクター研究会』, オンライン, 口頭報告, 2022年3月.

3.  **寺下和宏**「女性運動はジェンダー予算にいかなる影響をもたらすのか：韓国の地方自治体を事例に」, 『政治学若手フォーラム』, オンライン, 口頭報告, 2021年11月. [[Reference](https://sites.google.com/view/jecps/2021%E7%A7%8B)]{.btn}

### Work in Progress

#### Women's Organization and Gender Policy in Korea

1.  **\[Re-submitted\]** 女性団体と福祉政策――韓国における自治体福祉予算の実証分析

2.  Feminist Protests and Gender Policies: Empirical Evidence on Gender Budgeting in Korea

3.  Policy Process for Gentrification of Red-light Districts(RLDs) in Korea

4.  女性団体と選挙――参与観察を通じた女性団体の選挙へのコミットメントの解明

5.  女性団体・運動は女性の実質的代表に影響を与えるのか：韓国の議会議事録を用いた実証分析

#### Women's Organization and Gender Policy in Japan

6.  日本の市民社会における女性の政治的代表

7.  日本における女性団体の新聞報道の偏り

8.  日本の地域女性団体の運動とジェンダー政策

#### Automatized Protest Event Analysis in Asia

9.  抗議イベント分析の自動化/半自動化

### Awards

1.  「博士（政治学） 秀逸 summa cum laude / 神戸大学大学院法学研究科」, 2023年3月.

2.  「日本学生支援機構第一種奨学金特に優れた業績による返還免除（一部免除）」, 2019年5月.

3.  「2018年度立命館大学大学院リサーチプロポーザルコンテスト・敢闘賞」 題目：「『対立』する市民社会の政治分析：日韓『慰安婦』問題を事例に」, 2018年11月. [[Reference](http://www.ritsumei.ac.jp/ru_gr/g-career/news/article.html/?id=226)]{.btn}

4.  「2017年卒坂本治也ゼミ最優秀論文賞」,「坂本治也ゼミ第2代歴代最優秀論文賞」, 2017年3月. [[Reference](http://www2.itc.kansai-u.ac.jp/~haruya/zemipage.html)]{.btn}

### Founding

1.  \[単独\] 2023年4月-2026年3月：科学研究費 特別研究員奨励費「マイノリティ政策と市民社会の政治的代表：韓国・地方自治体の外国人支援政策を事例に」 [[KAKEN](https://kaken.nii.ac.jp/grant/KAKENHI-PROJECT-23KJ1150/)]{.btn}

2.  \[単独\] 2022年4月-6月：神戸大学異分野共創による次世代卓越博士人材育成プロジェクト 令和４年度プレミアム・プログラム「女性団体と選挙：韓国・慶尚南道議員候補の参与観察を通じて」（受入機関：延世大学国際学大学院）

3.  \[単独\] 2022年4月-2023年3月：神戸大学異分野共創による次世代卓越博士人材育成プロジェクト（JST次世代研究者挑戦的研究プログラム事業）「女性団体はジェンダー政策をもたらすか――韓国における地方自治体を事例に」

4.  \[単独\] 2022年4月-2023年3月：サントリー文化財団 若手研究者による社会と文化に関する個人研究助成（鳥井フェローシップ）「女性団体がジェンダー政策をもたらすとき――日本における地域女性団体の比較研究」 [[Reference](https://www.suntory.co.jp/sfnd/research/list_torii/2021.html)[報告書](https://www.suntory.co.jp/sfnd/research/detail/2021403.html)]{.btn}

5.  \[単独\] 2021年8月-2022年3月：日本学術振興会 若手研究者海外挑戦プログラム「社会運動がもたらす政治的成果の規定要因研究――韓国・女性政策の事例比較を通じて」（受入機関：延世大学国際学大学院・派遣先：大韓民国） [[Reference](https://www.jsps.go.jp/j-abc/R3.html)[報告書](https://www.jsps.go.jp/j-abc/data/R3/02/202180179_Terashita.pdf)]{.btn}

6.  \[単独\] 2018年11月：立命館大学大学院 博士課程前期課程研究実践活動補助金　国外フィールドリサーチ活動（活動地域 大韓民国）

7.  \[単独\] 2018年6月：立命館大学大学院 博士課程前期課程学生学会奨学金（支援対象学会：『日本NPO学会第20回研究大会』）

8.  \[単独\] 2018年6月：立命館大学大学院 学生研究会活動支援制度（研究会名：「総合政治学研究会」＊代表者として申請）

9.  \[単独\] 2017年4月, 2018年6月：立命館大学大学院 成績優秀者奨学金 ＊成績上位25%対象
